consumes:
- application/json
definitions:
  ConfigActionRequest:
    properties:
      args:
        description: Command arguments.
        items:
          description: Single command argument.
          example: -al
          type: string
        type: array
      cmd:
        description: Command.
        type: string
    required:
    - cmd
    type: object
  ConfigParameterRequest:
    properties:
      path:
        description: Key path
        items:
          description: Path item.
          example: period
          type: string
        type: array
      scheme:
        description: Scheme.
        example: yaml
        type: string
      source:
        description: Source filename.
        example: filebeat.yml
        type: string
      value:
        description: Parameter new value.
        example: 10s
        type: string
    required:
    - scheme
    - source
    - value
    type: object
  ConfigRequest:
    properties:
      actions:
        description: List of actions.
        items:
          $ref: '#/definitions/ConfigActionRequest'
        type: array
      parameters:
        description: List of parameters.
        items:
          $ref: '#/definitions/ConfigParameterRequest'
        type: array
      resources:
        description: List of resources.
        items:
          $ref: '#/definitions/ConfigResourceRequest'
        type: array
    type: object
  ConfigResourceRequest:
    properties:
      content:
        description: Resource content.
        type: string
      destination:
        description: Destination filename
        example: filebeat.yml
        type: string
    required:
    - content
    - destination
    type: object
  ConfigResponse:
    properties:
      results:
        items:
          $ref: '#/definitions/ConfigResultResponse'
        type: array
      when:
        description: Datetime of the configuration changes
        example: 2020/02/13 15:27:06
        format: date-time
        type: string
    required:
    - results
    - when
    type: object
  ConfigResultResponse:
    properties:
      type:
        description: Configuration type.
        type: string
      warning:
        description: Warning message
        example: 'Useless property: id'
        type: string
    required:
    - type
    type: object
  HTTPError:
    properties:
      description:
        description: Human readable message that describes the error.
        example: Could not decode the request body, either because it was not valid
          JSON or because it was not encoded as UTF-8.
        type: string
      title:
        description: Title error
        example: 400 Bad Request
        type: string
    required:
    - description
    - title
    type: object
  StatusResponse:
    properties:
      id:
        description: ID of the execution environment.
        example: apache
        type: string
      last_heartbeat:
        description: Timestamp of the last hearthbeat between the LCP and the CB
        example: 2019_02_14 15:23:33
        format: date-time
        type: string
      started:
        description: Timestamp when the LCP is started
        example: 2019_02_14 15:23:30
        format: date-time
        type: string
    required:
    - id
    - last_heartbeat
    - started
    type: object
info:
  title: Local Control Plane
  version: 1edeee00c413e586de55ee5f6d2769cadeb3771e@master
paths:
  /code:
    get: {}
    post: {}
  /config:
    get:
      description: Get the history of configuration updates.
      responses:
        '200':
          description: History of the configuration updates.
          schema:
            items:
              oneOf:
              - ConfigActionResponseSchema
              - ConfigParameterResponseSchema
              - ConfigResourceResponseSchema
            type: array
        '400':
          description: Bad Request.
          schema:
            $ref: '#/definitions/HTTPError'
        '401':
          description: Unauthorized.
          schema:
            $ref: '#/definitions/HTTPError'
      summary: Configuration update history
      tags:
      - config
    post:
      description: Apply configuration changes to the local environment.
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/ConfigRequest'
          type: array
      responses:
        '200':
          description: Configuration changes executed.
          schema:
            items:
              $ref: '#/definitions/ConfigResponse'
            type: array
        '400':
          description: Bad request.
          schema:
            $ref: '#/definitions/HTTPError'
        '401':
          description: Unauthorized.
          schema:
            $ref: '#/definitions/HTTPError'
      summary: Configuration update
      tags:
      - config
  /status:
    get:
      description: Get info about the status of the LCP in the execution environment.
      responses:
        '200':
          description: Status data of the LCP.
          schema:
            $ref: '#/definitions/StatusResponse'
        '401':
          description: Unauthorized.
          schema:
            $ref: '#/definitions/HTTPError'
      summary: Status info
      tags:
      - status
    post:
      description: Set the last heartbeat.
      responses:
        '200':
          description: Status data of the LCP.
          schema:
            $ref: '#/definitions/StatusResponse'
        '401':
          description: Unauthorized.
          schema:
            $ref: '#/definitions/HTTPError'
      summary: Status set.
      tags:
      - status
produces:
- application/json
swagger: '2.0'
tags:
- description: Code injection at run-time.
  name: code
- description: Configuration at run-time.
  name: config
- description: Status data of the LCP.
  name: status
