Get the history of configuration updates.
---
summary: Configuration update history
description: Get the history of configuration updates.
tags: [config]
responses:
  200:
    description: History of the configuration updates.
    schema:
      type: array
      items:
        oneOf:
          - ConfigActionResponseSchema
          - ConfigParameterResponseSchema
          - ConfigResourceResponseSchema
  400:
    description: Bad Request.
    schema: HTTPErrorSchema
  401:
    description: Unauthorized.
    schema: HTTPErrorSchema
